### ISSUE TITLE
proposal peer review

### ISSUE THREAD

**Issue by krileyy** [math241s24/project-02-t1w#1]
---
name: Proposal peer review
about: Peer review of project proposal
title: Proposal peer review
labels: ''
assignees: ''
---

The following is the peer review of the project proposal by t1w. The team members that participated in this review are 

project-02-state_constitution
- Cassie Minicucci - @cassiejm1
- Basil-Anne Stackpole - @bstackpole
- Katie Riley - @krileyy
- ...

- Describe the goal of the project.

To scrape data from immigration and immigration policy repos and create a spatial visualization of these data. Looking at the correlation between immigration levels and policies over time.

- Describe the data used or collected.

The data will be scraped from the department of homeland security, the data from the states of interest will be the only data scraped. Data is numbers of lawful permanent residents, nonimmigrants, naturalizations, asylees, refugees over the past 10 years.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.

They will research changes in sanctuary city policy from 2013-2022 in their chosen states, wrangle the data for ease of use (using pivot_longer and other functions) and then use the data to create a geospatial visualization of the sanctuary states.

- Is there anything that is unclear from the proposal?

Are the geospatial visualizations by state, or mapped together on a section of a US map? What are the variables you are mapping (ex: number of immigrants, type of policy?)

How are you differentiating the number of immigrants, naturalizations, asylees, etc. in the state at large versus in the “sanctuary cities”?

You have information on where you will get data on total arrivals, but I am curious where you are getting the policy data and how are you are incorporating it to determine correlation?

- Provide constructive feedback on how the team might be able to improve their project.

Being more specific with what variables in terms of policy you're looking at would be helpful- in other words, how is policy translated into a variable in your chosen dataset?

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.

The relationship between the policies of each state and their recorded numbers of lawful permanent residents, nonimmigrants, naturalizations, asylees, and refugees will be really interesting to see. 

- Provide constructive feedback on any issues with file and/or code organization.

It is not entirely clear in the “plan of attack” which group member will perform which task.

- (Optional) Any further comments or feedback?

This looks so cool!! Excited to see your presentation :D

**Comment by JamesAas** [comment]
The issue was for a previous iteration of the project, the research question and data changed, so it is no longer relevant to our project.
